# Generated by Django 6.0.5 on 2026-06-19 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('jawaban', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qnas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='QuizMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_materi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_materis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', models.TextField()),
                ('opsi_a', models.TextField()),
                ('opsi_b', models.TextField()),
                ('opsi_c', models.TextField()),
                ('opsi_d', models.TextField()),
                ('jawaban_benar', models.CharField(max_length=1)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='ai_features.quizmateri')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_materi', models.TextField()),
                ('hasil_summary', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
