# Generated by Django 4.2 on 2026-06-30 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_features', '0002_alter_qna_id_alter_quiz_id_alter_quizmateri_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizmateri',
            options={},
        ),
        migrations.RenameField(
            model_name='quizmateri',
            old_name='tanggal',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='quizmateri',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizmateri',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizmateri',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
