# Generated by Django 4.2.22 on 2026-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0003_alter_quiz_options_alter_quizmateri_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmateri',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
