# Generated by Django 4.2.22 on 2026-07-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0004_quizmateri_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmateri',
            name='is_pinned',
        ),
    ]
